Master:
  ServiceType: NodePort
  NodePort: 32000
  ContainerEnv:
    - name: JENKINS_URL
      value: http://192.168.99.100:32000
  CustomConfigMap: false

Persistence:
  Enabled: false

## Install Default RBAC roles and bindings
rbac:
  install: true
  serviceAccountName: jenkins-master
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: admin
  # Role kind (RoleBinding or ClusterRoleBinding)
  roleBindingKind: ClusterRoleBinding